---
title: "Results"
author: "Shubila Balaile"
date: '2021-04-12'
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,fig.width=10, fig.height=6)
#clear the global environment
rm(list = ls(all.names = TRUE))

library(tidyverse)
library(readxl)
library(tidyverse)
library("mlr")
library("iml")
library("future")
library("future.callr")
library("ggplot2")
library(gridExtra)

rename_pred <- read_excel("../documentation/Rename_predictors.xlsx",sheet = "Rename",col_names = TRUE)
load("../output/ml_object/caret/partial/test_train_partial_data.RData")
load("../output/ml_object/caret/partial/rf_partial_model.RData")


```


## Results - 2-way pdp:s

The partial function tells us for given value(s) of features S what the average marginal effect on the prediction is.

```{r resp_cat_work_neg, echo=FALSE}


plotdf <- function(tab,feature,lab1,lab2) {
      pdp_rf_pdp    <- tab %>%
        rename({{lab1}} := {{feature}})%>%
       mutate({{lab2}}  := "1-way pdp")%>%
       mutate({{lab2}}  := factor({{lab2}}))
  return(pdp_rf_pdp)
}



pdp2_df <- function(tab,feature1,lab1,feature2,lab2) {
  
  
  pdp2    <- tab %>%
    rename({{lab1}} := {{feature1}},
           {{lab2}} := {{feature2}},
           )
  return(pdp2)
}

pdp2_plot <- function(tab1,tab2,lab1,lab2) {
 
  pdp2plot_1 <- tab1  %>%
      ggplot(.,aes({{lab1}},{{lab2}}, fill =.value)) +
      geom_tile()
  
  pdp2plot_2 <- tab1 %>%
     ggplot(.,aes({{lab1}},.value, group = {{lab2}}, color = {{lab2}} )) +
      geom_line() +
      geom_line(data = tab2,size = 2,
            color = "gold"
            ) 
  
  
  graph_list <- list(pdp2plot_1,pdp2plot_2)
  
  return(graph_list)
}

predictor_rf_caret    = Predictor$new(rf_train_output_partial, data = lgbti_partial_test, class = "Open",type = "prob")


plan("callr", workers = 2)

pdp_rf       = FeatureEffect$new(predictor_rf_caret, feature = "G1_B", method = "pdp")


pdp_open_friend   <- plotdf(tab    =  pdp_rf$results,
                           feature = G1_B,
                           lab1    = open_friend,
                           lab2    = work_neg)


pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_B","C6_1_D"), method = "pdp")

pdp2_tab  <- pdp2_df( tab   = pdp2_rf$results,
                      feature1 = G1_B,
                      lab1     = open_friend,
                      feature2 = C6_1_D,
                      lab2     = work_neg)
                   
                     

work_neg_open_friend_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_friend,
                         lab1     = open_friend,
                         lab2     = work_neg)

work_neg_open_friend_graphs

############  positive work ####################

pdp_open_friend   <- plotdf(tab    =  pdp_rf$results,
                           feature = G1_B,
                           lab1    = open_friend,
                           lab2    = work_supp)


pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_B","C7_B"), method = "pdp")

pdp2_tab  <- pdp2_df( tab   = pdp2_rf$results,
                      feature1 = G1_B,
                      lab1     = open_friend,
                      feature2 = C7_B,
                      lab2     = work_supp)
                   
                     

work_supp_open_friends_graphs <- pdp2_plot(tab1     = pdp2_tab,
                                           tab2     = pdp_open_friend,
                                           lab1     = open_friend,
                                           lab2     = work_supp)

work_supp_open_friends_graphs



```


```{r resp_cat_ctry, echo=FALSE}


plan("callr", workers = 2)

pdp_rf$set.feature("A10")

pdp_ctry  <- plotdf(tab    =  pdp_rf$results,
                   feature = A10,
                   lab1    = ctry,
                   lab2    = work_neg) %>%
                  mutate(ctry = fct_recode(ctry,
                                "AT"   = "Austria",
                                "BE"   = "Belgium",
                                "BG"   = "Bulgaria",
                                "HR"   = "Croatia",
                                "CY"   = "Cyprus",
                                "CZ"   = "Czech Republic",
                                "DK"   = "Denmark",
                                "EE"   = "Estonia",
                                "FI"   = "Finland",
                                "FR"   = "France",
                                "DE"   = "Germany",
                                "GR"   = "Greece",
                                "HU"   = "Hungary",
                                "IE"   = "Ireland",
                                "IT"   = "Italy",
                                "LV"   = "Latvia",
                                "LT"   = "Lithuania",
                                "LU"   = "Luxembourg",
                                "MT"   = "Malta",
                                "NL"   = "Netherlands",
                                "PL"   = "Poland",
                                "PT"   = "Portugal",
                                "RO"   = "Romania",
                                "SK"   = "Slovakia",
                                "SI"   = "Slovenia",
                                "ES"   = "Spain",
                                "SE"   = "Sweden",
                                "UK"   = "United Kingdom",
                                "MK"   = "North Macedonia",
                                "RS"   = "Serbia"
                            )
         )



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("A10","C6_1_D"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = A10,
                      lab1     = ctry,
                      feature2 = C6_1_D,
                      lab2     = work_neg) %>%
                      mutate(ctry = fct_recode(ctry,
                                "AT"   = "Austria",
                                "BE"   = "Belgium",
                                "BG"   = "Bulgaria",
                                "HR"   = "Croatia",
                                "CY"   = "Cyprus",
                                "CZ"   = "Czech Republic",
                                "DK"   = "Denmark",
                                "EE"   = "Estonia",
                                "FI"   = "Finland",
                                "FR"   = "France",
                                "DE"   = "Germany",
                                "GR"   = "Greece",
                                "HU"   = "Hungary",
                                "IE"   = "Ireland",
                                "IT"   = "Italy",
                                "LV"   = "Latvia",
                                "LT"   = "Lithuania",
                                "LU"   = "Luxembourg",
                                "MT"   = "Malta",
                                "NL"   = "Netherlands",
                                "PL"   = "Poland",
                                "PT"   = "Portugal",
                                "RO"   = "Romania",
                                "SK"   = "Slovakia",
                                "SI"   = "Slovenia",
                                "ES"   = "Spain",
                                "SE"   = "Sweden",
                                "UK"   = "United Kingdom",
                                "MK"   = "North Macedonia",
                                "RS"   = "Serbia"
                            )
         )


ctry_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_ctry,
                         lab1     = ctry,
                         lab2     = work_neg)

ctry_work_neg_graphs


################ work positive #######################################

plan("callr", workers = 2)


pdp_ctry  <- plotdf(tab    =  pdp_rf$results,
                   feature = A10,
                   lab1    = ctry,
                   lab2    = work_supp) %>%
                  mutate(ctry = fct_recode(ctry,
                                "AT"   = "Austria",
                                "BE"   = "Belgium",
                                "BG"   = "Bulgaria",
                                "HR"   = "Croatia",
                                "CY"   = "Cyprus",
                                "CZ"   = "Czech Republic",
                                "DK"   = "Denmark",
                                "EE"   = "Estonia",
                                "FI"   = "Finland",
                                "FR"   = "France",
                                "DE"   = "Germany",
                                "GR"   = "Greece",
                                "HU"   = "Hungary",
                                "IE"   = "Ireland",
                                "IT"   = "Italy",
                                "LV"   = "Latvia",
                                "LT"   = "Lithuania",
                                "LU"   = "Luxembourg",
                                "MT"   = "Malta",
                                "NL"   = "Netherlands",
                                "PL"   = "Poland",
                                "PT"   = "Portugal",
                                "RO"   = "Romania",
                                "SK"   = "Slovakia",
                                "SI"   = "Slovenia",
                                "ES"   = "Spain",
                                "SE"   = "Sweden",
                                "UK"   = "United Kingdom",
                                "MK"   = "North Macedonia",
                                "RS"   = "Serbia"
                            )
         )



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("A10","C7_B"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = A10,
                      lab1     = ctry,
                      feature2 = C7_B,
                      lab2     = work_supp) %>%
                      mutate(ctry = fct_recode(ctry,
                                "AT"   = "Austria",
                                "BE"   = "Belgium",
                                "BG"   = "Bulgaria",
                                "HR"   = "Croatia",
                                "CY"   = "Cyprus",
                                "CZ"   = "Czech Republic",
                                "DK"   = "Denmark",
                                "EE"   = "Estonia",
                                "FI"   = "Finland",
                                "FR"   = "France",
                                "DE"   = "Germany",
                                "GR"   = "Greece",
                                "HU"   = "Hungary",
                                "IE"   = "Ireland",
                                "IT"   = "Italy",
                                "LV"   = "Latvia",
                                "LT"   = "Lithuania",
                                "LU"   = "Luxembourg",
                                "MT"   = "Malta",
                                "NL"   = "Netherlands",
                                "PL"   = "Poland",
                                "PT"   = "Portugal",
                                "RO"   = "Romania",
                                "SK"   = "Slovakia",
                                "SI"   = "Slovenia",
                                "ES"   = "Spain",
                                "SE"   = "Sweden",
                                "UK"   = "United Kingdom",
                                "MK"   = "North Macedonia",
                                "RS"   = "Serbia"
                            )
         )


ctry_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_ctry,
                         lab1     = ctry,
                         lab2     = work_supp)

ctry_work_supp_graphs









  




```


```{r resp_cat_empl, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("H2")


pdp_empl   <- plotdf(tab    =  pdp_rf$results,
                   feature = H2,
                   lab1    = empl,
                   lab2    = work_neg) %>%
                          mutate(empl = fct_recode(empl,
                                "Paid work"   = "In paid work",
                                "Self-empl"   = "Self-employed",
                              "Unpaid work"   = "Unpaid/voluntary work",
                              "Unemployed"    = "Unemployed",
                              "Student"       = "Student or pupil",
                              "Retired"       = "Retired",
                              "Unable"        = "Unable to work-health problems",
                            "Domestic task"   = "Domestic tasks",
                            "Mili/Civil serv" = "Military/Civilian service",
                            "Other"           = "Other"
                           )
         )



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("H2","C6_1_D"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = H2,
                      lab1     = empl,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  %>%
                          mutate(empl = fct_recode(empl,
                                "Paid work"   = "In paid work",
                                "Self-empl"   = "Self-employed",
                              "Unpaid work"   = "Unpaid/voluntary work",
                              "Unemployed"    = "Unemployed",
                              "Student"       = "Student or pupil",
                              "Retired"       = "Retired",
                              "Unable"        = "Unable to work-health problems",
                            "Domestic task"   = "Domestic tasks",
                            "Mili/Civil serv" = "Military/Civilian service",
                            "Other"           = "Other"
                           )
         )


empl_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_empl,
                         lab1     = empl,
                         lab2     = work_neg)

empl_work_neg_graphs


################# work positive #########################
    
pdp_empl   <- plotdf(tab    =  pdp_rf$results,
                   feature = H2,
                   lab1    = empl,
                   lab2    = work_supp) %>%
                          mutate(empl = fct_recode(empl,
                                "Paid work"   = "In paid work",
                                "Self-empl"   = "Self-employed",
                              "Unpaid work"   = "Unpaid/voluntary work",
                              "Unemployed"    = "Unemployed",
                              "Student"       = "Student or pupil",
                              "Retired"       = "Retired",
                              "Unable"        = "Unable to work-health problems",
                            "Domestic task"   = "Domestic tasks",
                            "Mili/Civil serv" = "Military/Civilian service",
                            "Other"           = "Other"
                           )
         )



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("H2","C7_B"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = H2,
                      lab1     = empl,
                      feature2 = C7_B,
                      lab2     = work_supp)  %>%
                          mutate(empl = fct_recode(empl,
                                "Paid work"   = "In paid work",
                                "Self-empl"   = "Self-employed",
                              "Unpaid work"   = "Unpaid/voluntary work",
                              "Unemployed"    = "Unemployed",
                              "Student"       = "Student or pupil",
                              "Retired"       = "Retired",
                              "Unable"        = "Unable to work-health problems",
                            "Domestic task"   = "Domestic tasks",
                            "Mili/Civil serv" = "Military/Civilian service",
                            "Other"           = "Other"
                           )
         )


empl_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_empl,
                         lab1     = empl,
                         lab2     = work_supp)

empl_work_supp_graphs





 


```


```{r, resp_cat_avoid_hands, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("D1")


pdp_avoid_hands   <- plotdf(tab    =  pdp_rf$results,
                           feature = D1,
                           lab1    = avoid_hands,
                           lab2    = work_neg) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("D1","C6_1_D"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = D1,
                      lab1     = avoid_hands,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


avoid_hands_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                                tab2     = pdp_avoid_hands,
                                lab1     = avoid_hands,
                                lab2     = work_neg)

avoid_hands_work_neg_graphs


########## work positive ######################


pdp_avoid_hands   <- plotdf(tab    =  pdp_rf$results,
                           feature = D1,
                           lab1    = avoid_hands,
                           lab2    = work_supp) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("D1","C7_B"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = D1,
                      lab1     = avoid_hands,
                      feature2 = C7_B,
                      lab2     = work_supp)  


avoid_hands_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                                tab2     = pdp_avoid_hands,
                                lab1     = avoid_hands,
                                lab2     = work_supp)

avoid_hands_work_supp_graphs





```



```{r, resp_cat_satisf, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("G2")


pdp_satisf   <- plotdf(tab    =  pdp_rf$results,
                      feature = G2,
                      lab1    = satisf,
                      lab2    = work_neg) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G2","C6_1_D"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G2,
                      lab1     = satisf,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


satisf_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_satisf,
                         lab1     = satisf,
                         lab2     = work_neg)

satisf_work_neg_graphs


############## work positive ###################

pdp_satisf   <- plotdf(tab    =  pdp_rf$results,
                      feature = G2,
                      lab1    = satisf,
                      lab2    = work_supp) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G2","C7_B"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G2,
                      lab1     = satisf,
                      feature2 = C7_B,
                      lab2     = work_supp)  


satisf_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_satisf,
                         lab1     = satisf,
                         lab2     = work_supp)

satisf_work_supp_graphs


```
```{r, resp_cat_open_fam, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("G1_A")


pdp_open_fam   <- plotdf(tab    =  pdp_rf$results,
                        feature = G1_A,
                        lab1    = open_fam,
                        lab2    = work_neg) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_A","C6_1_D"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_A,
                      lab1     = open_fam,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


open_fam_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_fam,
                         lab1     = open_fam,
                         lab2     = work_neg)

open_fam_work_neg_graphs

################# work supp ##################

pdp_open_fam   <- plotdf(tab    =  pdp_rf$results,
                        feature = G1_A,
                        lab1    = open_fam,
                        lab2    = work_supp) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_A","C7_B"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_A,
                      lab1     = open_fam,
                      feature2 = C7_B,
                      lab2     = work_supp)  


open_fam_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_fam,
                         lab1     = open_fam,
                         lab2     = work_supp)

open_fam_work_supp_graphs




```
```{r, resp_cat_open_friend, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("G1_B")


pdp_open_friend   <- plotdf(tab    =  pdp_rf$results,
                        feature = G1_B,
                        lab1    = open_friend,
                        lab2    = work_neg) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_B","C6_1_D"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_B,
                      lab1     = open_friend,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


open_friend_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_friend,
                         lab1     = open_friend,
                         lab2     = work_neg)

open_friend_work_neg_graphs


################### work positive #################

pdp_open_friend   <- plotdf(tab    =  pdp_rf$results,
                        feature = G1_B,
                        lab1    = open_friend,
                        lab2    = work_supp) 



pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_B","C7_B"), method = "pdp")



pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_B,
                      lab1     = open_friend,
                      feature2 = C7_B,
                      lab2     = work_supp)  


open_friend_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_friend,
                         lab1     = open_friend,
                         lab2     = work_supp)

open_friend_work_supp_graphs




```

```{r,resp_cat_open_neigh, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("G1_C")


pdp_open_neigh    <- plotdf(tab    =  pdp_rf$results,
                           feature = G1_C,
                           lab1    = open_neigh,
                           lab2    = work_neg) 

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_C","C6_1_D"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_C,
                      lab1     = open_neigh,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


open_neigh_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_neigh,
                         lab1     = open_neigh,
                         lab2     = work_neg)
open_neigh_work_neg_graphs

############# work supp ################


pdp_open_neigh    <- plotdf(tab    =  pdp_rf$results,
                           feature = G1_C,
                           lab1    = open_neigh,
                           lab2    = work_supp) 

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_C","C7_B"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_C,
                      lab1     = open_neigh,
                      feature2 = C7_B,
                      lab2     = work_supp)  


open_neigh_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_neigh,
                         lab1     = open_neigh,
                         lab2     = work_supp)
open_neigh_work_supp_graphs





```

```{r,resp_cat_open_stud, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("G1_E")


pdp_open_stud    <- plotdf(tab    =  pdp_rf$results,
                           feature = G1_E,
                           lab1    = open_stud,
                           lab2    = work_neg) 

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_E","C6_1_D"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_E,
                      lab1     = open_stud,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


open_stud_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_stud,
                         lab1     = open_stud,
                         lab2     = work_neg)
open_stud_work_neg_graphs


############## work supp ###########


pdp_open_stud    <- plotdf(tab    =  pdp_rf$results,
                           feature = G1_E,
                           lab1    = open_stud,
                           lab2    = work_supp) 

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_E","C7_B"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_E,
                      lab1     = open_stud,
                      feature2 = C7_B,
                      lab2     = work_supp)  


open_stud_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_stud,
                         lab1     = open_stud,
                         lab2     = work_supp)
open_stud_work_supp_graphs


```


```{r,resp_cat_open_med, echo=FALSE}

plan("callr", workers = 2)

pdp_rf$set.feature("G1_H")


pdp_open_med    <- plotdf(tab      =  pdp_rf$results,
                           feature = G1_H,
                           lab1    = open_med,
                           lab2    = work_neg)

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_H","C6_1_D"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_H,
                      lab1     = open_med,
                      feature2 = C6_1_D,
                      lab2     = work_neg)


open_med_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_med,
                         lab1     = open_med,
                         lab2     = work_neg)
open_med_work_neg_graphs

############## work support


pdp_open_med    <- plotdf(tab      =  pdp_rf$results,
                           feature = G1_H,
                           lab1    = open_med,
                           lab2    = work_supp)

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("G1_H","C7_B"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = G1_H,
                      lab1     = open_med,
                      feature2 = C7_B,
                      lab2     = work_supp)


open_med_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_open_med,
                         lab1     = open_med,
                         lab2     = work_supp)
open_med_work_supp_graphs



```


```{r}

plan("callr", workers = 2)

pdp_rf$set.feature("A1")


pdp_age    <-      plotdf(tab      =  pdp_rf$results,
                           feature = A1,
                           lab1    = age,
                           lab2    = work_neg) 

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("A1","C6_1_D"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = A1,
                      lab1     = age,
                      feature2 = C6_1_D,
                      lab2     = work_neg)  


age_work_neg_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_age,
                         lab1     = age,
                         lab2     = work_neg)
age_work_neg_graphs

############### work positive #####################

pdp_age    <-      plotdf(tab      =  pdp_rf$results,
                           feature = A1,
                           lab1    = age,
                           lab2    = work_supp) 

pdp2_rf      = FeatureEffect$new(predictor_rf_caret, feature = c("A1","C7_B"), method = "pdp")


pdp2_tab  <- pdp2_df( tab       = pdp2_rf$results,
                      feature1  = A1,
                      lab1     = age,
                      feature2 = C7_B,
                      lab2     = work_supp)  


age_work_supp_graphs <- pdp2_plot(tab1     = pdp2_tab,
                         tab2     = pdp_age,
                         lab1     = age,
                         lab2     = work_supp)
age_work_supp_graphs


```




```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```

